### ISSUE TITLE
How to save my likes?

### ISSUE THREAD

**Issue by Laydmei** [bbolli/tumblr-utils#118]
Hello,
I would like to save my likes from my tumblr. But when I use the command for, half of the files are saved. On 7000 posts put in favorites that 1000 are saved.
Someone would know how to solve my problem?
thank you in advance
(Sorry for my english, it's not my native language)

**Comment by Cebtenzzre** [comment]
Dupe of #131 -- please search the issues next time.

**Comment by Cebtenzzre** [comment]
Please see #114.

**Comment by Cebtenzzre** [comment]
@Laydmei @bbolli Someone should set the title to "--likes only downloads 1000 posts".

**Comment by sldx12** [comment]
Trying with PR #114 I got the two errors. 
Running `python2 tumblr_backup.py -l blogname` I got: 
```
Traceback (most recent call last):                                         
  File "tumblr_backup.py", line 1335, in <module>
    tb.backup(account)
  File "tumblr_backup.py", line 692, in backup
    before_timestamp = soup['response']['_links']['next']['query_params']['before']
KeyError: 'next'
```

Running `python2 tumblr_backup.py --likes --outdir=/home/user/Documents/likes/ --save-audio -j blogname` I got: 

`HTTP Error 404: Not Found getting https://api.tumblr.com/v2/blog/blogname.tumblr.com/likes?reblog_info=true&api_key=[MY API KEY]&limit=1`

**Comment by Cebtenzzre** [comment]
@sldx12 `blogname.tumblr.com` shouldn't be in that URL. Did you accidentally put `blogname.tumblr.com` on the command line instead of `blogname`?

**Comment by sldx12** [comment]
@Cebtenzzre No, I didn't.

**Comment by Cebtenzzre** [comment]
@sldx12 My bad, I forgot about the `if '.' not in account:` part of get_api_url. What does https://postlimit.com/ say about the blog's "Shares Likes" status?

**Comment by sldx12** [comment]
@Cebtenzzre `Shares Likes: 	  	Yes [link]`

**Comment by Cebtenzzre** [comment]
@sldx12 Unfortunately, I can only reproduce the 404 if I intentionally mistype the name of a blog. If you copy `<blogname>.tumblr.com/likes` from the error and paste it into a web browser, and it goes to the likes page of the blog, please open a new issue for this.

**Comment by sldx12** [comment]
`<blogname>.tumblr.com/likes` in the web browser asks me to login. However, I checked my account settings again and likes are public. I ran both commands withtout --likes and they seemed to work well, even though I didn't let them finish because I have a lot of posts. Do you still want me to open a new issue?

**Comment by Cebtenzzre** [comment]
@sldx12 Yeah, open a new issue to track this, but in the new issue please tell us if any other versions/forks/commits of tumblr-utils that you've tried _can_ back up the likes of this blog. If this is caused by API weirdness, the fix could be as simple as using cookies ([my fork](https://github.com/Cebtenzzre/tumblr-utils/tree/svc) does this) or might require adapting OAuth support from PR #200 (if the API has decided that your likes aren't public for some reason).
