### ISSUE TITLE
Tumblr Backup: InvalidURL: nonnumeric port: ''

### ISSUE THREAD

**Issue by ohhdemgirls** [bbolli/tumblr-utils#52]
When doing `python get.py -x -t me the-ghoulnextdoor` (NSFW) hangs with..

```
Exception in thread Thread-1:sts 350 to 399 of 430
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "get.py", line 802, in handler
    work()
  File "get.py", line 560, in save_content
    append_try('regular-body')
  File "get.py", line 550, in append_try
    self.get_inline_image, elt
  File "/usr/lib/python2.6/re.py", line 151, in sub
    return _compile(pattern, 0).sub(repl, string, count)
  File "get.py", line 661, in get_inline_image
    saved_name = self.download_image(image_url, image_filename)
  File "get.py", line 678, in download_image
    image_response = urllib2.urlopen(image_url, timeout=HTTP_TIMEOUT)
  File "/usr/lib/python2.6/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.6/urllib2.py", line 1172, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.6/urllib2.py", line 1118, in do_open
    h = http_class(host, timeout=req.timeout) # will parse host:port
  File "/usr/lib/python2.6/httplib.py", line 657, in __init__
    self._set_hostport(host, port)
  File "/usr/lib/python2.6/httplib.py", line 682, in _set_hostport
    raise InvalidURL("nonnumeric port: '%s'" % host[i+1:])
InvalidURL: nonnumeric port: ''

the-ghoulnextdoor: 0 remaining posts to save
```

**Comment by bbolli** [comment]
Can't reproduce here; which revision are you using? Oh, and what is `get.py`? It's not part of this repo.

**Comment by ohhdemgirls** [comment]
Sorry, `get.py` is `tumblr_backup.py` (up to date) with a few changes to how it writes out the html and other bits unrelated to the actual downloading. I can't seem to reproduce this now either!! Odd.
